services:
  db:
    image: postgres:16-alpine
    container_name: ox_pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: ox_user
      POSTGRES_PASSWORD: ox_pass
      POSTGRES_DB: ox_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
